### ISSUE TITLE
Add option to set path to ffmpeg binaries

### ISSUE THREAD

**Issue by positlabs** [damianociarla/node-ffmpeg#18]
Having a configurable path would make node-ffmpeg play nicely with ffmpeg-static. We wouldn't need to depend on the user having ffmpeg installed locally.

**Comment by wilsonwc** [comment]
Sounds reasonable, can you submit a PR?

**Comment by positlabs** [comment]
I've spent a total of 5 minutes using this lib, so please check my work. I think it's pretty straightforward, though.

**Comment by wilsonwc** [comment]
Thanks!

**Comment by JuanCrg90** [comment]
:+1:

**Comment by wilsonwc** [comment]
#19 was merged
