### ISSUE TITLE
video.save() does not support paths with spaces

### ISSUE THREAD

**Issue by ajmas** [damianociarla/node-ffmpeg#21]
Trying to call save() with a path that has a space in it results in the following (truncated):

`{ [Error: Command failed: /bin/sh -c ffmpeg -i /Users/ajmas/Development/projects/VideoTools/Saved Tracks/20160412115124.MOV -f mp4 /my/output/path/20160412115124.MOV.mp4
...
/Users/ajmas/Development/projects/VideoTools/Saved: No such file or directory
`

The code should be adjusted to support paths with spaces in them.

**Comment by damianociarla** [comment]
Thank you all for the support :-)

**Comment by Sy9876** [comment]
#23 I got same problem. 
Following error is occured on windows.
	'FlickAnimation.avi': No such file or directory
The executed command is
```
ffmpeg -i "'FlickAnimation.avi'" -r 1 ...
```
The single quotes are redundant.

**Comment by ajmas** [comment]
@Sy9876 best open a new ticket. This one was closed and for a slightly different behaviour.
