### ISSUE TITLE
Support for whitespace and special characters in input file name.

### ISSUE THREAD

**Issue by hiralbest** [damianociarla/node-ffmpeg#29]
If input file name contains whitespace or special character than this library breaks at run time.

**Comment by hiralbest** [comment]
Hi,

I see this issue is fixed as per the code in GitHub repository.
The code which we get using "npm install ffmpeg" does not have the latest code as I see in Github repository. 

Thanks.

**Comment by 2ec0b4** [comment]
Hello,
You can do this: `$ npm install damianociarla/node-ffmpeg`

**Comment by hiralbest** [comment]
Thanks @2ec0b4 .
