### ISSUE TITLE
Use BufferData instead of file path?

### ISSUE THREAD

**Issue by wsaunders1014** [damianociarla/node-ffmpeg#41]
Hi, not sure if this is the right place, but wondering if it's possible to use the buffer data from a file upload so I don't have to save the file until after ffmpeg is done working with it. Right now the user uploads a video, and I save it to a temp folder then run ffmpeg and output it to a new folder, but wondering if there was a way to streamline the process so I don't have to save the temp file.

**Comment by wilsonwc** [comment]
This library does not support reading from streams, you might look into the fluent-ffmpeg library https://github.com/fluent-ffmpeg/node-fluent-ffmpeg
