### ISSUE TITLE
Potentially unhandled rejection | FFMPEG throws a unsupported format Error message

### ISSUE THREAD

**Issue by AsP3X** [damianociarla/node-ffmpeg#51]
I've created a script to convert a mp4 in a webm file but i got an error message that is not related to the script it self because the script works fine on my ubuntu **desktop** pc with node js installed.

But the script throws an error message in my project and testing docker container.
The **docker container** is running on the **latest version** of ubuntu for docker.

**DESKTOP**
**Nodejs version: 9.11.1
npm version: 6.2.0**

**DOCKER CONTAINER
Nodejs version 10.7.0 (Also tried on the same version gave me the same result)
npm version 6.2.0**

Install command for all programs: 
`apt-get update && apt-get upgrade && apt-get install -y curl git nano htop && apt-get install -y gnupg2 && curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs && npm install npm -g`

Script: [Bitbucket / converter script](https://bitbucket.org/snippets/nodemod/EeL6pz/convert-mp4-to-webm)

ERROR Message: 
`Potentially unhandled rejection [1] {"code":104,"msg":"The format \"$s\" is not supported by the version of ffmpeg webm"} (WARNING: non-Error used)`

**Comment by ZombyMedia** [comment]
Project Tree:

Mainfolder /
- converter.js
- /src/
- - movie.mp4

**Comment by olaferlandsen** [comment]
same here, when using h264 + aac

**Comment by olaferlandsen** [comment]
Well, I change `node-ffmpeg` for [node-fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg)

**Comment by ChrisCates** [comment]
Got the same issue.
Not sure how this repository is even usable.

**Comment by zahra-ove** [comment]
I'd have same problem, the reason for me was because FFMPEG was not installed on the server. for example for ubuntu server, the ffmpeg can install by `sudo apt-get install ffmpeg'.
